#!/bin/bash

# This script will change the ownership of an application to the currently logged-in User. Helpful for when
# MDM-installed software is causing authorization issues.

# Target application - Use the text under "Name & Extensions" within Finder -> Get Info
application="Slack.app"

# Full path - Combines the root path and application to create the full path
fullPath="/Applications/$application"

# Get the current logged-in username
loggedInUser=$(stat -f %Su /dev/console)

# Get the current owner of the target application
currentOwner=$(stat -f %Su "$fullPath")

# Check if the current user is the owner
if [ "$loggedInUser" != "$currentOwner" ]; then
    echo "Current user is not the owner of $application. Changing ownership..."

    # Use the chown command to change ownership
    sudo chown -R "$loggedInUser" "$fullPath"

    # Check if chown was successful
    if [ $? -eq 0 ]; then
        echo "Ownership changed successfully."
    else
        echo "Error: Failed to change ownership."
        exit 1
    fi
else
    echo "Current user is already the owner of $application. No action needed."
fi

exit 0